#8==========> :)))))) 
#imBoutaCuuuuuum
#plzDontReadThis
#i totally licensed this so if you copy i will cut your nuts

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1
spec: 
  selector:
    matchLabels:
      app: team1
  template:
    metadata:
      labels:
        apps: team1
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsgroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      -name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "INSERT IMAGE LINK HERE"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: 8080