#8==========> :)))))) 
#imBoutaCuuuuuum
#plzDontReadThis
#i totally licensed this so if you copy i will cut your nuts

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1
spec: 
  selector:
    matchLabels:
      app: team1
  template:
    metadata:
      labels:
        apps: team1
    spec:
      serviceAccountName: default
      