apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: ux-prod-read
  namespace: ux-prod
spec:
  rules:
  - services: ["*.ux-prod.svc.cluster.local"]
    methods: ["GET", "HEAD"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: webdesign-prod-read
  namespace: webdesign-prod
spec:
  rules:
  - services: ["*.webdesign-prod.svc.cluster.local"]
    methods: ["GET", "HEAD"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: connectionsecurity-prod-read
  namespace: connectionsecurity-prod
spec:
  rules:
  - services: ["*.connectionsecurity-prod.svc.cluster.local"]
    methods: ["GET", "HEAD"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: datasearch-prod-read
  namespace: datasearch-prod
spec:
  rules:
  - services: ["*.datasearch-prod.svc.cluster.local"]
    methods: ["GET", "HEAD"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: mediaacquisition-prod-read
  namespace: mediaacquisition-prod
spec:
  rules:
  - services: ["*.mediaacquisition-prod.svc.cluster.local"]
    methods: ["GET", "HEAD"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: mediaplayer-prod-read
  namespace: mediaplayer-prod
spec:
  rules:
  - services: ["*.mediaplayer-prod.svc.cluster.local"]
    methods: ["GET", "HEAD"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: subscription-prod-read
  namespace: subscription-prod
spec:
  rules:
  - services: ["*.subscription-prod.svc.cluster.local"]
    methods: ["GET", "HEAD"]